all:
  children:
    guacamole:
      hosts:
        guacamole-dev:
          ansible_host: 52.201.46.244
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/roczyno/.ssh/cylynk-lab-keypair
          environment_type: dev  # renamed from 'environment'
          project_name: cyberlab
          domain_name: ""
          admin_email: "dev-admin@yourdomain.com"
          enable_lets_encrypt: false
          guacamole_db_password: "ChangeMe!SetARealPassword123"
    
    attackbox:  # Add this section
      hosts:
        attackbox-dev-1:
          ansible_host: 54.82.10.85
          ansible_user: kali  # or ubuntu
          ansible_ssh_private_key_file: /home/roczyno/.ssh/cylynk-lab-keypair
          environment_type: dev
          project_name: cyberlab